logging:
  level:
    ROOT:
      INFO
    #    org:
    #      springframework:
    #        web: DEBUG
    org:
      hibernate:
        SQL_SLOW: INFO
  config: classpath:log4j-spring.xml
server:
  port: 8086
  servlet:
    context-path: /alpha-sound
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ssl:
    enabled: true
    enabled-protocols: TLSv1.2
    key-alias: ${SSL_KEY_ALIAS:}
    key-password: ${SSL_KEY_PASSWORD:}
    key-store: classpath:vengeance.jks
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
    key-store-type: JKS
    protocol: TLS
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME:}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 100000
      maxLifetime: 900000
      maximum-pool-size: 20
      minimum-idle: 10
    tomcat:
      connection-properties: stringtype=unspecified
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        proc:
          param_null_passing: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 25
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: alpha_sound
        format_sql: true
        jdbc:
          batch_size: 20
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: static/i18n/message
  web:
    locale: en_US
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${AUTH_SERVICE:}
          client-id: ${CLIENT_ID:}
          client-secret: ${CLIENT_SECRET:}
        jwt:
          jwk-set-uri: ${JWKS_ENDPOINT:}
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:}
    port: ${REDIS_PORT:}
    database: ${REDIS_DB:}
    password: ${REDIS_PASSWORD:}
  kafka:
    bootstrap-servers: 'vengeance-kafka-1:9092,vengeance-kafka-2:9093,vengeance-kafka-3:9094'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: vengeance
      max-poll-records: 100
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    jaas:
      enabled: false
      options:
        topic-prefix: ""
  elasticsearch:
    rest:
      uris: ${ES_URL:}
      username: ${ES_USERNAME:}
      password: ${ES_PASSWORD:}
storage:
  storage-type: local
  temp: ${TEMP_DIR:}
  cloudinary:
    url: ${CLOUDINARY_URL:}
  firebase:
    database-url: ${FIREBASE_DATABASE_URL:}
    storage-bucket: ${FIREBASE_STORAGE_BUCKET:}
    credentials: ${FIREBASE_CREDENTIALS:}
  local:
    upload-root-uri: ${UPLOAD_ROOT_URI}
    upload-dir: ${UPLOAD_DIR:}
custom:
  http-port: 8085
  https-port: 8086
  security-policy: CONFIDENTIAL
  connector-scheme: http
  trust-store-password: ${SSL_TRUSTSTORE_PASSWORD:}
  trust-store-type: JKS
